#%RAML 1.0 Trait

traits:
# HTTP Success codes
  success_list_paged_200: !include definitions/success_list_paged_200.raml
  success_list_200: !include definitions/success_list_200.raml
  success_200: !include definitions/success_200.raml 
  success_201: !include definitions/success_201.raml
  success_201_xml: !include definitions/success_201_xml.raml
  success_202: !include definitions/success_202.raml      
  nullvalue_204: !include definitions/nullvalue_204.raml