#%RAML 1.0
title: s-wmos-api

description: This API will allow the consumer to carry out the following transactions; create, list, read, update and cancel
version: v1
protocols: [HTTPS]
baseUri: https://s-wmos-api/api/mawmos/ecp/v1/
mediaType: application/json
documentation:
  - !include docs/api_doc.raml

securitySchemes:
  basic: !include exchange_modules/58493d81-dbbb-4d5a-ad09-8b6a5da52369/common-api-security/1.0.10/securityFragments/basicAuthentication/Basic-Authentication.raml
  oAuth2_0: !include exchange_modules/58493d81-dbbb-4d5a-ad09-8b6a5da52369/common-api-security/1.0.10/securityFragments/oAuth2.0Security/OAuth2-Security-Scheme.raml
  clientIdAuth: !include exchange_modules/58493d81-dbbb-4d5a-ad09-8b6a5da52369/common-api-security/1.0.10/securityFragments/clientIdEnforcement/clientID-enforced-headers.raml
  
securedBy: [clientIdAuth]

uses: 
  globalWMSDataTypes: exchange_modules/58493d81-dbbb-4d5a-ad09-8b6a5da52369/warehousing-common-datatypes/1.0.22/warehousing-common-datatypes.raml
  errorDatatypes: exchange_modules/58493d81-dbbb-4d5a-ad09-8b6a5da52369/common-fault-messages/1.0.5/common-fault-messages.raml
  resourceMethods: exchange_modules/58493d81-dbbb-4d5a-ad09-8b6a5da52369/common-resource-types/1.0.3/common-resource-types.raml
  securitySchemes: exchange_modules/58493d81-dbbb-4d5a-ad09-8b6a5da52369/common-api-security/1.0.10/common-api-security.raml
  localDataTypes: /libraries/localDataTypesLibrary.raml


traits: 
  paginated: !include exchange_modules/58493d81-dbbb-4d5a-ad09-8b6a5da52369/common-api-traits/1.0.4/definitions/pagination.raml
  traceable: !include /exchange_modules/58493d81-dbbb-4d5a-ad09-8b6a5da52369/common-api-traits/1.0.4/definitions/traceable.raml
  wmosToken: !include /exchange_modules/58493d81-dbbb-4d5a-ad09-8b6a5da52369/common-api-traits/1.0.4/definitions/wmos-token.raml


# HTTP Success codes
  success_list_paged_200: !include exchange_modules/58493d81-dbbb-4d5a-ad09-8b6a5da52369/common-response-messages/1.0.0/definitions/success_list_paged_200.raml
  success_list_200: !include exchange_modules/58493d81-dbbb-4d5a-ad09-8b6a5da52369/common-response-messages/1.0.0/definitions/success_list_200.raml
  success_200: !include exchange_modules/58493d81-dbbb-4d5a-ad09-8b6a5da52369/common-response-messages/1.0.0/definitions/success_200.raml 
  success_201: !include exchange_modules/58493d81-dbbb-4d5a-ad09-8b6a5da52369/common-response-messages/1.0.0/definitions/success_201.raml
  success_201_xml: !include exchange_modules/58493d81-dbbb-4d5a-ad09-8b6a5da52369/common-response-messages/1.0.0/definitions/success_201_xml.raml
  success_202: !include exchange_modules/58493d81-dbbb-4d5a-ad09-8b6a5da52369/common-response-messages/1.0.0/definitions/success_202.raml      
  nullvalue_204: !include exchange_modules/58493d81-dbbb-4d5a-ad09-8b6a5da52369/common-response-messages/1.0.0/definitions/nullvalue_204.raml

# HTTP Error codes
  err_400: !include exchange_modules/58493d81-dbbb-4d5a-ad09-8b6a5da52369/common-fault-messages/1.0.5/traits/err_400.raml
  err_401: !include exchange_modules/58493d81-dbbb-4d5a-ad09-8b6a5da52369/common-fault-messages/1.0.5/traits/err_401.raml
  err_404: !include exchange_modules/58493d81-dbbb-4d5a-ad09-8b6a5da52369/common-fault-messages/1.0.5/traits/err_404.raml
  err_405: !include exchange_modules/58493d81-dbbb-4d5a-ad09-8b6a5da52369/common-fault-messages/1.0.5/traits/err_405.raml
  err_406: !include exchange_modules/58493d81-dbbb-4d5a-ad09-8b6a5da52369/common-fault-messages/1.0.5/traits/err_406.raml
  err_407: !include exchange_modules/58493d81-dbbb-4d5a-ad09-8b6a5da52369/common-fault-messages/1.0.5/traits/err_407.raml
  err_415: !include exchange_modules/58493d81-dbbb-4d5a-ad09-8b6a5da52369/common-fault-messages/1.0.5/traits/err_415.raml
  err_500: !include exchange_modules/58493d81-dbbb-4d5a-ad09-8b6a5da52369/common-fault-messages/1.0.5/traits/err_500.raml
  err_503: !include exchange_modules/58493d81-dbbb-4d5a-ad09-8b6a5da52369/common-fault-messages/1.0.5/traits/err_503.raml
  err_504: !include exchange_modules/58493d81-dbbb-4d5a-ad09-8b6a5da52369/common-fault-messages/1.0.5/traits/err_504.raml        



  
#######################################################################################################
                                    #DO NOT EDIT ABOVE THIS LINE#
#######################################################################################################
  


/authentication:
  type:  
    resourceMethods.collection_types:
      postDescription: This service allows the consumer to Sign In and Sign Out of Manhattan Associates WMOS
      postRequestType: globalWMSDataTypes.authentication
      postRequestExample: !include examples/requests/authentication.json
      postResponseExample_201: !include examples/responses/authentication/success_201.json
      postResponseExample_202: !include examples/responses/authentication/success_202.json
  post:
      is: [traceable]
  /validate: 
    /contextID:
      type:  
        resourceMethods.collection_types:
          postDescription: This service allows applications to check the validity of context IDs
          postRequestType: globalWMSDataTypes.authentication
          postRequestExample: !include examples/requests/authentication.json
          postResponseExample_201: !include examples/responses/authentication/success_201.json
          postResponseExample_202: !include examples/responses/authentication/success_202.json
      post:
       is: [traceable]
    /businessUnit:
      type:  
        resourceMethods.collection_types:
          postDescription: This service allows applications to check access to business units
          postRequestType: globalWMSDataTypes.authentication
          postRequestExample: !include examples/requests/authentication.json
          postResponseExample_201: !include examples/responses/authentication/success_201.json
          postResponseExample_202: !include examples/responses/authentication/success_202.json
      post:
        is: [traceable]
        
/inbound:
  /purchaseOrder:
    type: 
      resourceMethods.collection_types: 
      #createPurchaseOrder
        postDescription: This service allows users to create a new Purchase Order for a particular Business Unit 
        postRequestType: globalWMSDataTypes.purchaseOrder
        postRequestExample: !include examples/requests/purchase_order.json
        postResponseExample_201: !include examples/responses/purchaseOrder/post_success_201.json
        postResponseExample_202: !include examples/responses/success_202.json
    post:
      is: [traceable, wmosToken]
    /{purchaseOrderNumber}:
        type: 
          resourceMethods.collection_types:
            #updatePurchaseOrder
              putDescription: This service allows users to update Purchase Order for a particular Business Unit
              putRequestType: globalWMSDataTypes.purchaseOrder
              putRequestExample: !include examples/requests/purchase_order.json
              putResponseType: globalWMSDataTypes.purchaseOrder
              putResponseExample:  !include examples/responses/purchaseOrder/put_success_202.json
              putResponseExample_202: !include examples/responses/purchaseOrder/put_success_202.json
            #cancelPurchaseOrder
              deleteDescription: This service can be used to cancel Purchase Order for a particular Business Unit
              deleteRequestType: nil
              deleteRequestExample: null
              deleteResponseType: globalWMSDataTypes.purchaseOrder
              deleteResponseExample:  !include /examples/responses/purchaseOrder/delete_success_202.json
              deleteResponseExample_202:  !include /examples/responses/purchaseOrder/delete_success_202.json
        put:
          is: [traceable, wmosToken]
        delete:
          is: [traceable, wmosToken]
          queryParameters:
            businessUnit:
              description: Business Unit of the Item
              type: string
              required: true
        /close:
            type: 
              resourceMethods.collection_types:
                #closePurchaseOrder
                  putDescription: This service can be used to close Purchase Order for a particular Business Unit
                  putRequestType: globalWMSDataTypes.purchaseOrder
                  putRequestExample: !include examples/requests/purchase_order.json
                  putResponseType: globalWMSDataTypes.purchaseOrder
                  putResponseExample: !include examples/responses/purchaseOrder/put_success_200.json
                  putResponseExample_202: !include examples/responses/purchaseOrder/put_success_200.json
            put:
              is: [traceable, wmosToken]
              queryParameters: 
                businessUnit:
                  description: Business Unit of Purchase Order
                  type: string 
                  required: true
  /asn:
    type: 
      resourceMethods.collection_types:
        postDescription: This service is used to create the ASN information, based on the ASN number of the ASN for a Business Unit
        postRequestType: globalWMSDataTypes.asn
        postRequestExample: !include examples/requests/asn.json
        postResponseExample_201: !include examples/responses/asn/success_201.json
        postResponseExample_202: !include examples/responses/asn/success_202.json
    post:
      is: [traceable, wmosToken]
    /{asnNumber}: 
      type: 
        resourceMethods.collection_types:
          getDescription: This service is used to retrieve the ASN information, for a unique ASN record for a Business Unit
          getResponseType: globalWMSDataTypes.asn
          getResponseExample: !include examples/requests/asn.json     
          putDescription: This service is used to update the ASN information for a business unit (BU).
          putRequestType: globalWMSDataTypes.asn
          putRequestExample: !include /examples/requests/asn.json
          putResponseType: globalWMSDataTypes.asn
          putResponseExample: !include examples/responses/success_202.json
          putResponseExample_202: !include examples/responses/success_202.json 
      get:
        is: [traceable, wmosToken]
        queryParameters:
          businessUnit: 
            description: Business Unit of the Item
            type: string
            required: true
      put:
        is: [traceable, wmosToken]
      /quantityReceived:
        type:
          resourceMethods.collection_types:
            getDescription: This service is used to retrieve the quanity recieved 
            getResponseType: globalWMSDataTypes.asn
            getResponseExample: !include /examples/responses/asn/asn.json  
        get:
          is: [traceable, wmosToken]
      /lpnReceived:
        type:
          resourceMethods.collection_types:
            getDescription: This service is used to retrieve the LPN recieved 
            getResponseType: globalWMSDataTypes.asn
            getResponseExample: !include /examples/responses/asn/asn.json
        get:
          is: [traceable, wmosToken]

/outbound:
  /distributionOrders:
    type: 
      resourceMethods.collection_types: 
      #CreateDistributionOrder 
        postDescription: This service allows to create a distribution order
        postRequestType: globalWMSDataTypes.distributionOrders
        postRequestExample: !include examples/requests/distribution_orders.json
        postResponseExample_201: !include examples/responses/success_201.json
        postResponseExample_202: !include examples/responses/success_202.json
      #listCurrentOpen
        getDescription: This service allows to read a list of distribution orders for a particular Business Unit
        getResponseType: globalWMSDataTypes.distributionOrdersList
        getResponseExample: !include /examples/responses/distributionOrder/list_distribution_order.json
    post:
      is: [traceable, wmosToken]
    get:
      is: [traceable, wmosToken]
      queryParameters:
        businessUnit:
          description: Business Unit of the Item
          type: string
          required: true
        orderKeyOnly:
          description: Order Key 
          type: string
          required: false
        doNumber:
          description: Distribution order number
          type: string
          required: false
        pageSize:
          description: Total number of records to be fetched
          type: integer
          required: true
        pageIndex:
          description: Page index from which the records are to be fetched
          type: integer
          required: true
        limit:
          description: Limit number of product records
          type: integer
          required: false
    /{distributionOrderNumber}:
      type: 
        resourceMethods.collection_types:
        #getDistributionOrder
          getDescription: This service allows to view all the distribution orders for a particular Business Unit
          getResponseType: globalWMSDataTypes.distributionOrders
          getResponseExample: !include /examples/responses/distributionOrder/distribution_orders.json
        #updateDistributionOrder
          putDescription: This service allows to update a dictibution order for a particuar Business Unit
          putRequestType: globalWMSDataTypes.distributionOrders
          putRequestExample: !include examples/requests/distribution_orders.json
          putResponseType: globalWMSDataTypes.distributionOrders
          putResponseExample:  !include examples/responses/distributionOrder/put_success_202.json
          putResponseExample_202: !include examples/responses/distributionOrder/put_success_202.json
        #cancelDistributionOrder
          deleteDescription: This servive allows to cancel a specific distribution order
          deleteRequestType: nil
          deleteRequestExample: null
          deleteResponseType: globalWMSDataTypes.distributionOrders
          deleteResponseExample:  !include examples/responses/distributionOrder/delete_success_202.json
          deleteResponseExample_202:  !include examples/responses/distributionOrder/delete_success_202.json        
      get:
        is: [traceable, wmosToken]
        queryParameters:
          businessUnit: 
            description: Business Unit of the Item
            type: string
            required: true
      put:
        is: [traceable, wmosToken]
      delete:
        is: [traceable, wmosToken]
        queryParameters:
          businessUnit:
            description: Business Unit of the Item
            type: string
            required: true

/masterdata:
        /product:
          type:
            resourceMethods.collection_types:
            #POST method to create a new products
              postDescription: This service allows to create a new product
              postRequestType: globalWMSDataTypes.product
              postRequestExample: !include /examples/requests/product.json
              postResponseExample_201: !include examples/responses/product/post_success_201.json
              postResponseExample_202: !include examples/responses/product/post_success_201.json
            #GET method for current products
              getDescription: This service fetches an array of products passed through the post method
              getResponseType: globalWMSDataTypes.productList
              getResponseExample: !include /examples/responses/product/list_product.json
          post:
            is: [traceable, wmosToken]
          get:
            is: [traceable, wmosToken]
            queryParameters:
              businessUnit:
                description: Business Unit of the Item
                type: string
                required: true
              productKeyOnly:
                description: 
                type: string
                required: true
              businessPartner:
                description: Customer or supplier
                type: string
                required: false
              pageSize:
                description: Total number of records to be fetched
                type: integer
                required: true
              pageIndex:
                description: Page index from which the records are to be fetched
                type: integer
                required: true
              limit:
                description: Limit number of product records
                type: integer
                required: false                 
          /{productIdentifier}:
            type: 
              resourceMethods.collection_types:
              #GET method for product information
                getDescription: This service is used to get the product information
                getResponseType: globalWMSDataTypes.product
                getResponseExample: !include /examples/responses/product/product.json
              #PUT method to update products
                putDescription: This service allows the user to update a product that is available 
                putRequestType: globalWMSDataTypes.product
                putRequestExample: !include examples/requests/product.json
                putResponseType: globalWMSDataTypes.product
                putResponseExample:  !include examples/responses/product/put_success_202.json
                putResponseExample_202: !include examples/responses/product/put_success_202.json
              #DELETE method to DELETE products
                deleteDescription: This service allows the user to mark a product as “Cancelled”
                deleteRequestType: nil
                deleteRequestExample: null
                deleteResponseType: globalWMSDataTypes.product
                deleteResponseExample:  !include examples/responses/product/delete_success_202.json
                deleteResponseExample_202:  !include examples/responses/product/delete_success_202.json
            get:
              is: [traceable, wmosToken]
            put:
              is: [traceable, wmosToken]
            delete:
              is: [traceable, wmosToken]    
              queryParameters:
                businessUnit:
                  description: Business Unit of the Item
                  type: string
                  required: true
                  
/reporting:
  /inventory:
    /holdings:
      type: 
        resourceMethods.collection_types:
        #GET method for product information
          getDescription: This serive allows the consumer to read Stock holding for a specific business unit
          getResponseType: globalWMSDataTypes.stockHoldings
          getResponseExample: !include examples/responses/stock/stock_holdings.json
      get:
        is: [traceable]    
        queryParameters:
          businessUnit:
            description: Business Unit of the Item
            type: number
            required: true
    /transactions:
      type: 
        resourceMethods.collection_types:
        #GET method for product information
          getDescription: This serive allows the consumer to extract Stock transactions for a specific period
          getResponseType: globalWMSDataTypes.stockTransactions
          getResponseExample: !include examples/responses/stock/stock_transactions.json
      get:
        is: [traceable]    
        queryParameters:
          businessUnit:
            description: Business Unit of the Item
            type: number
            required: true
          dateFrom:
            description: 
            type: string
            required: true