{
  "headers": {
    "client_id": "1d44ce44367b4f46910aa2433bcca039",
    "client_secret": "kjihi56b1212vghc35b34kb45k",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.26.10",
    "accept": "*/*",
    "postman-token": "5f66898f-6f13-45e2-99ef-347d84517245",
    "host": "localhost:8082",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "154"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "https",
  "queryParams": {"businessUnit":"100"},
  "requestUri": "/api/mawmos/epc/v1/WMOS/authentication",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/WMOS/authentication",
  "listenerPath": "/api/mawmos/epc/v1/*",
  "relativePath": "/api/mawmos/epc/v1/WMOS/authentication",
  "localAddress": "/127.0.0.1:8082",
  "uriParams": {},
  "rawRequestUri": "/api/mawmos/epc/v1/WMOS/authentication",
  "rawRequestPath": "/api/mawmos/epc/v1/WMOS/authentication",
  "remoteAddress": "/127.0.0.1:63874",
  "requestPath": "/api/mawmos/epc/v1/WMOS/authentication"
}