{
  "headers": {
    "content-type": "application/json",
    "client_id": "1d44ce44367b4f46910aa2433bcca039",
    "client_secret": "kjihi56b1212vghc35b34kb45k",
    "x-transaction-id": "DFFV45ERCEC",
    "user-agent": "PostmanRuntime/7.26.10",
    "accept": "*/*",
    "cache-control": "no-cache",
    "postman-token": "da0ba1e5-cf01-45ac-be55-91cb0071cdff",
    "host": "localhost:8092",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "230"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "https",
  "queryParams": {},
  "requestUri": "/api/mawmos/epc/v1/authentication",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/authentication",
  "listenerPath": "/api/mawmos/epc/v1/*",
  "relativePath": "/api/mawmos/epc/v1/authentication",
  "localAddress": "/127.0.0.1:8092",
  "uriParams": {},
  "rawRequestUri": "/api/mawmos/epc/v1/authentication",
  "rawRequestPath": "/api/mawmos/epc/v1/authentication",
  "remoteAddress": "/127.0.0.1:64385",
  "requestPath": "/api/mawmos/epc/v1/authentication"
}