{
  "headers": {
    "client_id": "a934bnj3n45ou5i7nln443b54b",
    "client_secret": "kjihi56b1212vghc35b34kb45k",
    "content-type": "application/json",
    "context_id": "kjihi56b1212vghc35b34kb45ds",
    "user-agent": "PostmanRuntime/7.26.10",
    "accept": "*/*",
    "postman-token": "f8ac9ca1-2567-45e2-955f-8f684d396d33",
    "host": "localhost:8082",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "384"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "https",
  "queryParams": {},
  "requestUri": "/api/mawmos/epc/v1/WMOS/authentication",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/WMOS/authentication",
  "listenerPath": "/api/mawmos/epc/v1/*",
  "relativePath": "/api/mawmos/epc/v1/WMOS/authentication",
  "localAddress": "/127.0.0.1:8082",
  "uriParams": {},
  "rawRequestUri": "/api/mawmos/epc/v1/WMOS/authentication",
  "rawRequestPath": "/api/mawmos/epc/v1/WMOS/authentication",
  "remoteAddress": "/127.0.0.1:55301",
  "requestPath": "/api/mawmos/epc/v1/WMOS/authentication"
}