#%RAML 1.0 Library
usage:

types:
  record: !include /dataTypes/record.raml
  singleRecord: !include /dataTypes/record.raml
  recordList: !include /dataTypes/recordList.raml 
  postmode_xml: !include /dataTypes/post_xml.xsd
  recordListPaged: !include /dataTypes/recordListPaged.raml