#%RAML 1.0 Library

types:
  asn: !include resourceTypes/ASN/ASNSchema.json
  distributionOrders: !include resourceTypes/distributionOrders/distributionOrderSchema.json
  distributionOrdersList: !include resourceTypes/distributionOrders/distributionOrderListSchema.json
  product: !include resourceTypes/product/productMasterSchema.json
  productList: !include resourceTypes/product/productListSchema.json
  purchaseOrder:  !include resourceTypes/purchaseOrder/purchaseOrderSchema.json
  WMSSecurity: !include resourceTypes/WMSSecurity/securitySchema.json