%dw 2.0
import * from dw::test::Asserts
---
payload must equalTo(
	{
  stockTransactions: [
    {
      warehouse: "ECP",
      businessUnit: "100",
      transactionType: "300",
      transactionCode: "01",
      transactionNumber: 205,
      sequenceNumber: 1,
      reasonCode: "null",
      actionCode: "05",
      SKU: "1001",
      LPN: "000000013",
      inventoryType: "null",
      batchNumber: "null",
      adjustmentType: "S",
      adjustmentQuantity: 100,
      processedDateTime: "2021-02-25T12:39:00"
    }, 
    {
      warehouse: "ECP",
      businessUnit: "100",
      transactionType: "300",
      transactionCode: "01",
      transactionNumber: 54,
      sequenceNumber: 2,
      reasonCode: "null",
      actionCode: "06",
      SKU: "1001",
      LPN: "000000001",
      inventoryType: "null",
      batchNumber: "null",
      adjustmentType: "A",
      adjustmentQuantity: 50,
      processedDateTime: "2021-02-25T12:04:00"
    }, 
    {
      warehouse: "ECP",
      businessUnit: "100",
      transactionType: "300",
      transactionCode: "01",
      transactionNumber: 57,
      sequenceNumber: 2,
      reasonCode: "null",
      actionCode: "06",
      SKU: "1001",
      LPN: "000000005",
      inventoryType: "null",
      batchNumber: "null",
      adjustmentType: "A",
      adjustmentQuantity: 100,
      processedDateTime: "2021-02-25T12:04:00"
    }, 
    {
      warehouse: "ECP",
      businessUnit: "100",
      transactionType: "300",
      transactionCode: "01",
      transactionNumber: 64,
      sequenceNumber: 2,
      reasonCode: "null",
      actionCode: "06",
      SKU: "1001",
      LPN: "000000006",
      inventoryType: "null",
      batchNumber: "null",
      adjustmentType: "A",
      adjustmentQuantity: 100,
      processedDateTime: "2021-02-25T12:04:00"
    }, 
    {
      warehouse: "ECP",
      businessUnit: "100",
      transactionType: "300",
      transactionCode: "01",
      transactionNumber: 101,
      sequenceNumber: 2,
      reasonCode: "null",
      actionCode: "06",
      SKU: "1001",
      LPN: "000000010",
      inventoryType: "null",
      batchNumber: "null",
      adjustmentType: "A",
      adjustmentQuantity: 10,
      processedDateTime: "2021-02-25T12:04:00"
    }, 
    {
      warehouse: "ECP",
      businessUnit: "100",
      transactionType: "300",
      transactionCode: "01",
      transactionNumber: 104,
      sequenceNumber: 2,
      reasonCode: "null",
      actionCode: "06",
      SKU: "1001",
      LPN: "000000011",
      inventoryType: "null",
      batchNumber: "null",
      adjustmentType: "A",
      adjustmentQuantity: 10,
      processedDateTime: "2021-02-25T12:04:00"
    }, 
    {
      warehouse: "ECP",
      businessUnit: "100",
      transactionType: "300",
      transactionCode: "01",
      transactionNumber: 107,
      sequenceNumber: 2,
      reasonCode: "null",
      actionCode: "06",
      SKU: "1001",
      LPN: "000000012",
      inventoryType: "null",
      batchNumber: "null",
      adjustmentType: "A",
      adjustmentQuantity: 50,
      processedDateTime: "2021-02-25T12:04:00"
    }, 
    {
      warehouse: "ECP",
      businessUnit: "100",
      transactionType: "300",
      transactionCode: "01",
      transactionNumber: 110,
      sequenceNumber: 2,
      reasonCode: "null",
      actionCode: "06",
      SKU: "1001",
      LPN: "000000013",
      inventoryType: "null",
      batchNumber: "null",
      adjustmentType: "A",
      adjustmentQuantity: 100,
      processedDateTime: "2021-02-25T12:04:00"
    }, 
    {
      warehouse: "ECP",
      businessUnit: "100",
      transactionType: "300",
      transactionCode: "01",
      transactionNumber: 51,
      sequenceNumber: 2,
      reasonCode: "null",
      actionCode: "06",
      SKU: "1001",
      LPN: "000000003",
      inventoryType: "null",
      batchNumber: "null",
      adjustmentType: "A",
      adjustmentQuantity: 60,
      processedDateTime: "2021-02-25T12:04:00"
    }, 
    {
      warehouse: "ECP",
      businessUnit: "100",
      transactionType: "300",
      transactionCode: "01",
      transactionNumber: 98,
      sequenceNumber: 2,
      reasonCode: "null",
      actionCode: "06",
      SKU: "1001",
      LPN: "000000009",
      inventoryType: "null",
      batchNumber: "null",
      adjustmentType: "A",
      adjustmentQuantity: 10,
      processedDateTime: "2021-02-25T12:04:00"
    }
  ]
}
)