{
  "headers": {
    "content-type": "application/json",
    "client_id": "a934bnj3n45ou5i7nln443b54b",
    "client_secret": "kjihi56b1212vghc35b34kb45k",
    "context-id": "12345",
    "x-transaction-id": "5VA342F4246",
    "user-agent": "PostmanRuntime/7.26.10",
    "accept": "*/*",
    "postman-token": "4c01f7bb-5e3b-4d04-99c8-a992ebfc17ee",
    "host": "localhost:8082",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "931"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "https",
  "queryParams": {"businessUnit":"1", productKeyOnly:"Y",
					businessPartner:"100",
					pageSize:"1",
					pageIndex:"1"},
  "requestUri": "/api/mawmos/epc/v1/WMOS/masterdata/product",
  "queryString": "businessUnit=1",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/WMOS/masterdata/product",
  "listenerPath": "/api/mawmos/epc/v1/*",
  "relativePath": "/api/mawmos/epc/v1/WMOS/masterdata/product",
  "localAddress": "/127.0.0.1:8082",
  "uriParams": {},
  "rawRequestUri": "/api/mawmos/epc/v1/WMOS/masterdata/product",
  "rawRequestPath": "/api/mawmos/epc/v1/WMOS/masterdata/product",
  "remoteAddress": "/127.0.0.1:50830",
  "requestPath": "/api/mawmos/epc/v1/WMOS/masterdata/product"
}