#%RAML 1.0 DocumentationItem
title:  s-wmos-api
content: |
    #  API
    The APIs shall be extendable to support multiple customer and multiple instances of Manhattan WMOS applications. These APIs enable the customer to perform operations on Manhattan Associates WMOS.
